### ISSUE TITLE
unit_of_measurement missing. Gives wrong "graph" in hass.

### ISSUE THREAD

**Issue by turbokongen** [heyajohnny/cryptoinfo#2]
The attribute `unit_of_measurement` is missing from the sensor.
This result in a non graph history.
![image](https://user-images.githubusercontent.com/16622752/83950834-e0660b00-a82d-11ea-84ba-61623ebe314a.png)
`currency_name` should be mapped to `unit_of_measurement` attribute.

**Comment by heyajohnny** [comment]
I've just added a default `unit_of_measurement` of "". 
This should fix your graph history.

I don't want to map the `currency_name` to the `unit_of_measurement`, because I personally find it annoying/takes away too much space in the UI.
You can of course change it yourself for every sensor in the 'ui-lovelace.yaml'

I hope this answers your questions. And as always, enjoy ;)

**Comment by heyajohnny** [comment]
I'm closing this issue
