### ISSUE TITLE
chart

### ISSUE THREAD

**Issue by jeroenduhboer** [heyajohnny/cryptoinfo#9]
Hello,
Is it possible to graph it?

**Comment by heyajohnny** [comment]
Sure you can. 
cryptoinfo is just a sensor that provides data at a certain time. 

You need a lovelace card that shows data in a graph / chart. I think you're looking for something like this: https://github.com/kalkih/mini-graph-card
Or this:
https://www.home-assistant.io/lovelace/history-graph/

I'm closing the issue, since it's not part of this sensor. 
You can still add comments to the issue if you can't get it to work.
